# Generated by Django 5.1.1 on 2024-09-28 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=255, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=255, verbose_name='Region')),
                ('population', models.IntegerField(null=True, verbose_name='Population')),
                ('area', models.FloatField(null=True, verbose_name='Area (sq. mi.)')),
                ('population_density', models.FloatField(null=True, verbose_name='Pop. Density (per sq. mi.)')),
                ('coastline', models.FloatField(null=True, verbose_name='Coastline (coast/area ratio)')),
                ('net_migration', models.FloatField(null=True, verbose_name='Net migration')),
                ('infant_mortality', models.FloatField(null=True, verbose_name='Infant mortality (per 1000 births)')),
                ('gdp', models.FloatField(null=True, verbose_name='GDP ($ per capita)')),
                ('literacy', models.FloatField(null=True, verbose_name='Literacy (%)')),
                ('phones', models.FloatField(null=True, verbose_name='Phones (per 1000)')),
                ('arable', models.FloatField(null=True, verbose_name='Arable (%)')),
                ('crops', models.FloatField(null=True, verbose_name='Crops (%)')),
                ('other', models.FloatField(null=True, verbose_name='Other (%)')),
                ('climate', models.FloatField(null=True, verbose_name='Climate')),
                ('birthrate', models.FloatField(null=True, verbose_name='Birthrate')),
                ('deathrate', models.FloatField(null=True, verbose_name='Deathrate')),
                ('agriculture', models.FloatField(null=True, verbose_name='Agriculture')),
                ('industry', models.FloatField(null=True, verbose_name='Industry')),
                ('service', models.FloatField(null=True, verbose_name='Service')),
            ],
        ),
    ]
